// Código generado automáticamente. No editar.
namespace myImages {

    helpers._registerFactory("image", function(name: string) {
        switch(helpers.stringTrim(name)) {
            case "image1":
            case "miImagen":return img`
........................
.....ffff...............
...fff22fff.............
..fff2222fff............
.fffeeeeeefff...........
.ffe222222eef...........
.fe2ffffff2ef...........
.ffffeeeeffff...........
ffeddddddddeff..........
feedffddffdeef..........
.ffffdddddeef...........
fddddf444eef............
fbbbbf2222f4e...........
fbbbbf2222fd4...........
.fccf45544f44...........
..ffffffff..............
....ff..ff..............
........................
........................
........................
........................
........................
........................
........................
`;
        }
        return null;
    })

    helpers._registerFactory("animation", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

    helpers._registerFactory("song", function(name: string) {
        switch(helpers.stringTrim(name)) {

        }
        return null;
    })

}
// Código generado automáticamente. No editar.
